import {
  button,
  iconButton,
  iconButtons,
  fab,
  segmentedButtons,
} from "./buttons";
import {
  toggle,
  checkbox,
  radio,
  pills,
  slider,
  knob,
  stepper,
  rating,
  progress,
} from "./controls";
import {
  tabs,
  appBar,
  navBar,
  pagination,
  steps,
  drawer,
  menu,
} from "./navigation";
import { searchBar, input, select, searchView } from "./inputs";
import { calendar, timePicker, datePicker } from "./pickers";
import {
  accordion,
  rows,
  table,
  badge,
  carousel,
  card,
  tooltip,
} from "./content";
import { dialog, sheet, snackbar } from "./overlays";
import { scaffold } from "./screens";
import {
  gridColumns,
  gridBaseline,
  gridSquare,
  gridSafe,
  gridThirds,
} from "./grids";

import { ARCHITECTURE_COMPONENTS } from "./architecture";
import { FLOW_COMPONENTS } from "./flow";
import { PROGRAMMING_COMPONENTS } from "./programming";
import { STATE_COMPONENTS } from "./state";

import type { ComponentDef, Values } from "../shapes";

export const PARAMETRIC: readonly ComponentDef[] = [
  gridColumns,
  gridBaseline,
  gridSquare,
  gridSafe,
  gridThirds,
  scaffold,
  fab,
  segmentedButtons,
  drawer,
  searchView,
  datePicker,
  tooltip,
  button,
  iconButton,
  iconButtons,
  toggle,
  checkbox,
  radio,
  slider,
  knob,
  stepper,
  rating,
  input,
  searchBar,
  select,
  pills,
  badge,
  progress,
  snackbar,
  card,
  carousel,
  accordion,
  rows,
  table,
  tabs,
  appBar,
  navBar,
  pagination,
  steps,
  menu,
  dialog,
  sheet,
  calendar,
  timePicker,
  ...FLOW_COMPONENTS,
  ...STATE_COMPONENTS,
  ...ARCHITECTURE_COMPONENTS,
  ...PROGRAMMING_COMPONENTS,
];

/** the fixed components these replace */
export const REPLACED = new Set([
  "button-primary",
  "button-secondary",
  "button-ghost",
  "button-danger",
  "button-icon",
  "button-icon-soft",
  "button-group",
  "checkbox-on",
  "checkbox-off",
  "radio-on",
  "radio-off",
  "toggle-on",
  "toggle-off",
  "slider",
  "slider-range",
  "slider-labeled",
  "knob",
  "knob-small",
  "stepper",
  "rating",
  "chips",
  "tabs",
  "segmented",
  "pagination",
  "steps",
  "list-simple",
  "list-switch",
  "table",
  "navbar",
  "bottom-nav",
  "calendar",
  "time-picker",
  "menu",
  "dialog",
  "sheet",
  "toast",
  "badge",
  "badge-count",
  "progress",
  "progress-labeled",
  "progress-ring",
  "tooltip",
  "input-text",
  "input-search",
  "input-password",
  "input-labeled",
  "input-error",
  "input-select",
  "card",
]);

export type { Values };
